version: '3.5'

services:
  api:
    container_name: order-service
    build: .
    environment:
      DB_USER: admin
      DB_PASS: admin
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/project
    ports:
      - 8002:8002
    depends_on:
      - db
  
  db:
    container_name: order-service-db
    image: postgres:latest
    # command: printenv
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata:
    driver: local