# Generated by Django 2.2.5 on 2019-09-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddsItens',
            fields=[
                ('adds_name', models.CharField(max_length=50)),
                ('adds_quantity', models.IntegerField()),
                ('adds_price', models.FloatField()),
                ('adds_description', models.TextField(max_length=100)),
                ('adds_number_identification', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('number_identification', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
